### ISSUE TITLE
Mount Failed

### ISSUE THREAD

**Issue by TheBatmanWhoLaughs13** [ChendoChap/Playstation-4-Save-Mounter#12]
So I was following step by step on how to use someone else save by decrypting it 1st but when I go to mount it it shows mount failed. It's my own save from non JB PS4 but the last time the save was modified was in February of 2018 and if I'm not mistaken it still should have been saved with 5.05 keys as the next FW of 5.50 didn't release until the following month.

What else would cause it not to mount? Or does it fail to mount because it's saved on a higher firmware

**Comment by ChendoChap** [comment]
did you extract said save when the ps4 was still on 5.05?
afaik the playstation (resigns/repackages) your saves when you use the save data utilities, so exported saves always use the latest keyset.

**Comment by TheBatmanWhoLaughs13** [comment]
Yeah, I copied them to USB on the latest firmware.

So regardless of the save was made on a firmware lower then 5.05, the transfer encrypts them with the latest keys?

**Comment by ChendoChap** [comment]
As far as I could tell, yes that's exactly what it does. So you can't transfer the saves to your 5.05 console the opposite however works just fine, you can transfer any save from a 5.05 console to a 5.05+ console as long as the destination account has psn capabilities (otherwise you can't export your saves in settings)
