### ISSUE TITLE
Create Save create corrupts the PS4

### ISSUE THREAD

**Issue by protectivedad** [ChendoChap/Playstation-4-Save-Mounter#9]
I was moving a save from a parent title (Horizon Zero Dawn CUSA07320) to a child title (Horizon Zero Dawn - Complete Edition CUSA10213). I made the mistake of using the Create Save feature of the mounter. It created a save game, but I'm guessing since the CUSA07320 had never been installed on the PS4, it caused an issue. The save didn't show up in the game, it did show up in Settings/Storage but gave an error when trying to delete it, and from that point on no game on the PS4 could save anymore they would just error. I'm guessing a DB got corrupted because the CUSA07320 was used when the actual game was CUSA10213.

In case you are not familiar the CUSA10213 uses the CUSA07320 id for all its save games. I don't know how you'd be able to figure that out but if the Save Mounter had a "Delete Save" feature at least it could remove the problem save so the PS4 doesn't have to be reset. I was thinking a nice feature would be when creating a save to put "Playstation 4 Save Mounter Save" in the description and then let the application delete only those saves that it has created.

**Comment by ChendoChap** [comment]
I'm sorry to hear that,
letting save mounter delete saves wouldn't really fix your issue (as that would probably have the same problem as your ps4 is having atm).
try deleting the save from the .db and removing its dir from your savedata dir. also make sure to copy the db and the rest of your saves while you're at it. so that if if worse comes to worst youd be able to restore them.

**Comment by Shinygati** [comment]
Got the exact same issue here... except in my case the injected save was somehow unreadable and got corrupted i guess but now i cannot make new saves on that game or any others, i have deleted all save related file to that title id and removed the entry from the .db file but it still does not work and i'm all out of idea's on what to do, really don't want to have to format my console from simply trying to edit a save file like this.

**Comment by Buzbee** [comment]
Try the ps4 database rebuilder

https://github.com/Zer0xFF/PS4_db_rebuilder/releases/tag/0.1

**Comment by ChendoChap** [comment]
I can't seem to replicate this behavior so it's rather difficult to debug could you capture uart output whilst trying to do anything save related? Also to be safe it's best to reboot before using the built in save options since this modifies some of the stuff it uses.

That rebuilder won't help you unless your actual game db is messed up, it doesn't touch saves afaik.
